#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define MAX_PATH_LENGTH 4097
#define MAX_CMD_LENGTH 4453
#define MAX_RESOURCE_LENGTH 256
#define BUFFER_SIZE 1024
#define BACKLOG 8
#define PROGRESS_BAR_WIDTH 50
#define TIME_OUT 36000

#endif
